version: 1
services:
  - type: web
    name: tu-nombre-de-servicio
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 app:app


